branches:
  only:
    - master
bundler_args: --without development --path=~/.bundle
language: ruby
sudo: false
rvm:
  2.3.1
before_script:
  - cp config/database.yml.example config/database.yml
  - mysql -e 'create database sample_railgular_test;'
  - bundle exec rake db:test:load
